# https://github.com/release-drafter/release-drafter/pull/424#issuecomment-598830640
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Check and Release New Version
    runs-on: ubuntu-latest
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
      # npm release
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get release version from tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # Node setup
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          always-auth: false
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      # Validate and publish
      - name: npm setup and validation
        run: |
          npm ci --engine-strict
          npm run setup

      - name: Publish New Package Version
        run: npm publish --provenance --access public
        env:
          NODE_ENV: production

      - name: Publish Release Notes
        uses: release-drafter/release-drafter@v6
        with:
          publish: true
          tag: ${{ env.RELEASE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
